web:
  restart: always
  build: ./web
  ports:
    - "5000:5000"
  links:
    - postgres:postgres
  volumes:
    - ./web:/usr/src/app
  env_file: .env
  tty: true
  command: python run.py

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
